import java.util.Scanner;

public class DiceGame {
	
	public static void main(String[] args)
	{
		Scanner input = new Scanner(System.in);
		
		int [] diceNumber = {1,2,3,4,5,6};
		int [] guess = new int[4];
		int game = 0;
		int again = 0;
		int even = 0;
		int odd = 0;
		int win = 0;
		int lose = 0;
		float percentage;
		int count = 1;

		
		System.out.println("Guess if the number generated by the system is even or odd");
		
		do{
			for (int i = 1; i < 4; i++)
		
			{
			
				System.out.printf("Game #%d:\n",i);
				
				System.out.print("Enter (1) for even or (0) for odd: ");
				guess[i] = input.nextInt();
			
				diceNumber[i] = 1 + (int) (Math.random() * 6);
			}
			
		
			for (int j = 1; j < 4; j++)
			{
				
				if (diceNumber[j]%2 == 0 && guess[j] == 1)
				{
					System.out.printf("Game #%d: The system generated %d, you guessed even, you win!\n",j,diceNumber[j]);
					even++;
					win++;
					game++;
				}
				if(diceNumber[j]%2 != 0 && guess[j] == 0)
				{
					System.out.printf("Game #%d: The system generated %d, you guessed odd, you win!\n",j,diceNumber[j]);
					odd++;
					win++;
					game++;
				}
				if (diceNumber[j]%2 == 0 && guess[j] == 0)
				{
					System.out.printf("Game #%d: The system generated %d, you guessed odd, you lose:-(\n",j, diceNumber[j]);
					even++;
					lose++;
					game++;
					}
				if(diceNumber[j]%2 != 0 && guess[j] == 1)
				{
					System.out.printf("Game #%d: The system generated %d, you guessed even, you lose:-(\n",j,diceNumber[j]);
					odd++;
					lose++;
					game++;
				}
			}
			
		
			System.out.print("Would you like to play another game? (1)yes or (0)no: ");
			again = input.nextInt();
		
			if (again == 0)
			{
				percentage = (float) ((win * 100) / game);
			
				System.out.printf("The total number of times you won were %d\n",win);
			
				System.out.printf("The total amount of times you lost were %d\n",lose);
			
				System.out.printf("The total number of games you played were %d\n",game);
			
				System.out.printf("The system generated %d number of evens and %d number of odds\n",even,odd);
			
				System.out.print("Your total winning percentage was " + percentage + "%\n");
			
				System.out.println("Thank you for playing, Good-bye");
			}
	}while(again == 1);
	}
}
		
			
		
